apiVersion: v1
kind: Service
metadata:
  name: grasshopper-api-host
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "environment=EKS"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    role: grasshopper-api
  ports:
    - name: api
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grasshopper-api
  labels:
    role: grasshopper-api
spec:
  selector:
    matchLabels:
      role: grasshopper-api
  template:
    metadata:
      labels:
        role: grasshopper-api
    spec:
      initContainers:
        - name: wait-locust-master
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nslookup locust-master-host; do echo waiting locust-master-host; sleep 2; done;",
            ]
      containers:
        - image: latrova/grasshopper-dashboard-api:latest
          name: grasshopper-api
          imagePullPolicy: Always
          env:
            - name: LOCUST_HOST
              value: http://locust-master-host
            - name: DB_TABLE_NAME
              value: grasshopper_data
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: ECS_CLUSTER_NAME
              value: CLUSTERNAME # CHANGE HERE
            - name: ECS_ENVIRONMENT
              value: Perf # CHANGE HERE
            - name: RDS_NAME_FILTER
              value: perf-db-prefix # CHANGE HERE
            - name: AWS_ACCESS_KEY
              value: YOUR_KEY # CHANGE HERE
            - name: AWS_SECRET_KEY
              value: YOUR_KEY # CHANGE HERE
          ports:
            - containerPort: 3000
