apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  labels:
    role: master
spec:
  selector:
    matchLabels:
      role: master
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        role: master
    spec:
      containers:
        - image: locustio:latest # Update to your image
          imagePullPolicy: Always
          name: locust-master
          env:
            - name: LOCUST_MODE
              value: MASTER
            - name: LOCUST_OPTS
              value: --csv=report
          envFrom:
            - configMapRef:
                name: locust-config
          ports:
            - containerPort: 8089
              name: ui
            - containerPort: 5557
              name: comm
            - containerPort: 5558
              name: comm-plus-1
