version: "3.2"
services:
  ui:
    build:
      context: ../../ui
      dockerfile: Dockerfile.dev
      args:
        API_HOST: http://localhost:3000
    image: latrova/grasshopper-dashboard-ui:local
    ports:
      - "1234:1234"
      - "1235:1235"
    environment:
      NODE_ENV: "development"
      PARCEL_WORKERS: 1
    depends_on:
      - api

  api:
    build: ../../api
    image: latrova/grasshopper-dashboard-api:local
    ports:
      - "3000:3000"
    environment:
      LOCUST_HOST: "http://locust:8089"
    env_file:
      - ../../api/.env.default
      - ../../api/.env.local
    depends_on:
      - locust

  locust:
    build: ../locust
    image: locustio:local
    environment:
      LOCUST_OPTS: "--host https://google.com"
    ports:
      - "8089:8089"
